"""Generate an interactive Cursor Canvas for manual branch-point pairing.

Reads a TreeAnalysis run folder (the CSVs written by ``run_tree_analysis.py``)
and emits a single ``.canvas.tsx`` file that renders the whole-cell skeleton and
the FOV-mosaic skeleton side by side. You click a branch point on each side to
build correspondences; the canvas fits a live 2D similarity so you can *see* the
mosaic snap onto the cell, and prints the ``mosaic_n,cell_n`` pairs CSV to paste
into the config's ``branchpoint_pairs``.

Features for picking pairs:
- mosaic branch points are coloured by **FOV** (with a legend),
- each panel has a **depth (Z) slider** so overlapping XY points can be
  separated by depth.

Canvas data must be embedded inline (no file reads at runtime), so the skeletons
are decimated and baked straight into the generated component.

CLI:
    python make_registration_canvas.py results/<run> --session pre-droplet
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List

import pandas as pd

# Cursor canvases must be written into this managed workspace directory.
CANVAS_DIR = Path(r"C:/Users/Jackie/.cursor/projects/d-learning-project-spines/canvases")

# Distinct FOV colours (subset of the canvas colorPalette hues).
_FOV_PALETTE = [
    "#7B64B8F0",  # purple
    "#1F8A65E8",  # green
    "#E8C030E0",  # yellow
    "#C85898E0",  # pink
    "#2E79B5E0",  # blue
    "#F0A040E0",  # orange
    "#2A9A8AE0",  # teal
    "#C06028E0",  # deep orange
]


def _fov_of(graph: pd.DataFrame) -> Dict[int, str]:
    if "fov" not in graph.columns:
        return {}
    return {int(r["n"]): str(r["fov"]) for _, r in graph.iterrows()}


def _polylines(graph: pd.DataFrame, stride: int) -> List[dict]:
    """Decimated polylines per segment, connected to parent; carries fov + z."""
    coord: Dict[int, List[float]] = {
        int(r["n"]): [round(float(r["x_um"]), 1), round(float(r["y_um"]), 1), round(float(r["z_um"]), 1)]
        for _, r in graph.iterrows()
    }
    parent: Dict[int, int] = {int(r["n"]): int(r["parent"]) for _, r in graph.iterrows()}
    fov = _fov_of(graph)
    out: List[dict] = []
    for _, seg in graph.groupby("seg_id"):
        seg = seg.sort_values("path_to_soma")
        ns = [int(v) for v in seg["n"].tolist()]
        if not ns:
            continue
        pts: List[List[float]] = []
        p = parent.get(ns[0], -1)
        if p in coord:
            pts.append(coord[p])
        kept = ns[:: max(1, stride)]
        if ns[-1] not in kept:
            kept.append(ns[-1])
        pts.extend(coord[n] for n in kept)
        if len(pts) >= 2:
            out.append({"fov": fov.get(ns[0], ""), "pts": pts})
    return out


def _bps(bp: pd.DataFrame, graph: pd.DataFrame) -> List[dict]:
    fov = _fov_of(graph)
    return [
        {
            "n": int(r["n"]),
            "x": round(float(r["x_um"]), 1),
            "y": round(float(r["y_um"]), 1),
            "z": round(float(r["z_um"]), 1),
            "fov": fov.get(int(r["n"]), ""),
        }
        for _, r in bp.iterrows()
    ]


def _bounds(graph: pd.DataFrame) -> List[float]:
    return [round(float(graph["x_um"].min()), 1), round(float(graph["x_um"].max()), 1),
            round(float(graph["y_um"].min()), 1), round(float(graph["y_um"].max()), 1)]


def _zbounds(graph: pd.DataFrame) -> List[float]:
    return [round(float(graph["z_um"].min()), 1), round(float(graph["z_um"].max()), 1)]


def build_data(run_dir: Path, session: str, animal: str, stride: int) -> dict:
    cell_graph = pd.read_csv(run_dir / "cell_graph.csv")
    cell_bp = pd.read_csv(run_dir / "cell_bp.csv")
    mos_graph = pd.read_csv(run_dir / f"{session}_mosaic_graph.csv")
    mos_bp = pd.read_csv(run_dir / f"{session}_mosaic_bp.csv")

    fovs = sorted(str(v) for v in mos_graph.get("fov", pd.Series(dtype=str)).dropna().unique()) if "fov" in mos_graph.columns else []
    fov_colors = {f: _FOV_PALETTE[i % len(_FOV_PALETTE)] for i, f in enumerate(fovs)}

    return {
        "animal": animal,
        "session": session,
        "fovColors": fov_colors,
        "cell": {
            "polylines": _polylines(cell_graph, stride),
            "bps": _bps(cell_bp, cell_graph),
            "bounds": _bounds(cell_graph),
            "zbounds": _zbounds(cell_graph),
        },
        "mosaic": {
            "polylines": _polylines(mos_graph, max(1, stride // 2)),
            "bps": _bps(mos_bp, mos_graph),
            "bounds": _bounds(mos_graph),
            "zbounds": _zbounds(mos_graph),
        },
    }


_TSX_TEMPLATE = r"""// AUTO-GENERATED by make_registration_canvas.py. Edit the generator, not this file.
import { Card, CardBody, CardHeader, Stack, Row, Grid, H2, H3, Text, Button, Code, Callout, Pill, Stat, useHostTheme, useCanvasState } from "cursor/canvas";

type BP = { n: number; x: number; y: number; z: number; fov: string };
type Poly = { fov: string; pts: number[][] };
type Cloud = { polylines: Poly[]; bps: BP[]; bounds: number[]; zbounds: number[] };
type Data = { animal: string; session: string; fovColors: Record<string, string>; cell: Cloud; mosaic: Cloud };

const DATA: Data = /*DATA_JSON*/;

type Sim = { s: number; cos: number; sin: number; tx: number; ty: number };

function fitSimilarity(src: number[][], dst: number[][]): Sim | null {
  const n = src.length;
  if (n < 2) return null;
  let msx = 0, msy = 0, mdx = 0, mdy = 0;
  for (let i = 0; i < n; i++) { msx += src[i][0]; msy += src[i][1]; mdx += dst[i][0]; mdy += dst[i][1]; }
  msx /= n; msy /= n; mdx /= n; mdy /= n;
  let sumprod = 0, sumcross = 0, denom = 0;
  for (let i = 0; i < n; i++) {
    const xi = src[i][0] - msx, yi = src[i][1] - msy;
    const xj = dst[i][0] - mdx, yj = dst[i][1] - mdy;
    sumprod += xi * xj + yi * yj;
    sumcross += xi * yj - yi * xj;
    denom += xi * xi + yi * yi;
  }
  if (denom === 0) return null;
  const a = sumprod / denom, b = sumcross / denom;
  const s = Math.sqrt(a * a + b * b);
  const cos = a / s, sin = b / s;
  const tx = mdx - s * (cos * msx - sin * msy);
  const ty = mdy - s * (sin * msx + cos * msy);
  return { s, cos, sin, tx, ty };
}

function applySim(t: Sim, p: number[]): number[] {
  return [t.s * (t.cos * p[0] - t.sin * p[1]) + t.tx, t.s * (t.sin * p[0] + t.cos * p[1]) + t.ty];
}

function rms(t: Sim, src: number[][], dst: number[][]): number {
  let acc = 0;
  for (let i = 0; i < src.length; i++) {
    const m = applySim(t, src[i]);
    acc += (m[0] - dst[i][0]) ** 2 + (m[1] - dst[i][1]) ** 2;
  }
  return Math.sqrt(acc / Math.max(1, src.length));
}

const W = 340, H = 200, HPAD = 26;
function mapperXY(b: number[]) {
  const spanX = Math.max(1e-6, b[1] - b[0]), spanY = Math.max(1e-6, b[3] - b[2]);
  const sc = Math.min((W - 2 * HPAD) / spanX, (H - 2 * HPAD) / spanY);
  return (p: number[]): number[] => [HPAD + (p[0] - b[0]) * sc, H - HPAD - (p[1] - b[2]) * sc];
}

function mapperXZ(xb: number[], zb: number[]) {
  const spanX = Math.max(1e-6, xb[1] - xb[0]), spanZ = Math.max(1e-6, zb[1] - zb[0]);
  const sc = Math.min((W - 2 * HPAD) / spanX, (H - 2 * HPAD) / spanZ);
  return (p: number[]): number[] => [HPAD + (p[0] - xb[0]) * sc, H - HPAD - (p[2] - zb[0]) * sc];
}

function inSlice(z: number, center: number, half: number, on: boolean) {
  return !on || Math.abs(z - center) <= half;
}

function segInSlice(pts: number[][], center: number, half: number, on: boolean) {
  if (!on) return true;
  for (const p of pts) if (Math.abs(p[2] - center) <= half) return true;
  return false;
}

function bpById(cloud: Cloud): Record<number, BP> {
  const m: Record<number, BP> = {};
  for (const b of cloud.bps) m[b.n] = b;
  return m;
}

export default function RegistrationCanvas() {
  const theme = useHostTheme();
  const [pairs, setPairs] = useCanvasState<number[][]>("pairs", []);
  const [selCell, setSelCell] = useCanvasState<number | null>("selCell", null);
  const [selMosaic, setSelMosaic] = useCanvasState<number | null>("selMosaic", null);

  const cz0 = DATA.cell.zbounds[0], cz1 = DATA.cell.zbounds[1];
  const mz0 = DATA.mosaic.zbounds[0], mz1 = DATA.mosaic.zbounds[1];
  const [cellZ, setCellZ] = useCanvasState<number>("cellZ", (cz0 + cz1) / 2);
  const [mosZ, setMosZ] = useCanvasState<number>("mosZ", (mz0 + mz1) / 2);
  const [sliceCell, setSliceCell] = useCanvasState<boolean>("sliceCell", true);
  const [sliceMos, setSliceMos] = useCanvasState<boolean>("sliceMos", true);
  const [cellHalf, setCellHalf] = useCanvasState<number>("cellHalf", 20);
  const [mosHalf, setMosHalf] = useCanvasState<number>("mosHalf", 8);

  const cellMapXY = mapperXY(DATA.cell.bounds);
  const cellMapXZ = mapperXZ([DATA.cell.bounds[0], DATA.cell.bounds[1]], DATA.cell.zbounds);
  const mosMapXY = mapperXY(DATA.mosaic.bounds);
  const mosMapXZ = mapperXZ([DATA.mosaic.bounds[0], DATA.mosaic.bounds[1]], DATA.mosaic.zbounds);
  const cellBy = bpById(DATA.cell);
  const mosBy = bpById(DATA.mosaic);

  const src: number[][] = [], dst: number[][] = [];
  for (const pr of pairs) {
    const mn = pr[0], cn = pr[1];
    if (mosBy[mn] && cellBy[cn]) { src.push([mosBy[mn].x, mosBy[mn].y]); dst.push([cellBy[cn].x, cellBy[cn].y]); }
  }
  const fit = fitSimilarity(src, dst);
  const fitRms = fit ? rms(fit, src, dst) : null;

  function addPair() {
    if (selCell == null || selMosaic == null) return;
    if (pairs.some((p) => p[0] === selMosaic || p[1] === selCell)) return;
    setPairs([...pairs, [selMosaic, selCell]]);
    setSelCell(null); setSelMosaic(null);
  }
  function removePair(i: number) { setPairs(pairs.filter((_, j) => j !== i)); }

  const csv = "mosaic_n,cell_n\n" + pairs.map((p) => p[0] + "," + p[1]).join("\n");

  const sliceLine = (mapXZ: (p: number[]) => number[], center: number, half: number, on: boolean) => {
    if (!on) return null;
    const y = mapXZ([0, 0, center])[1];
    return <line x1={HPAD} y1={y} x2={W - HPAD} y2={y} stroke={theme.accent.primary} strokeWidth={1} strokeDasharray="4 3" opacity={0.7} />;
  };

  const drawPanel = (
    cloud: Cloud, map: (p: number[]) => number[], mapSide: (p: number[]) => number[],
    sel: number | null, onClick: (n: number) => void, fallback: string,
    center: number, half: number, sliceOn: boolean, byFov: boolean, proj: string,
  ) => (
    <Stack gap={4}>
      <Text size="small" tone="tertiary">{proj}</Text>
      <svg width={W} height={H} style={{ background: theme.bg.elevated, borderRadius: 6, border: "1px solid " + theme.stroke.tertiary }}>
        {sliceLine(mapSide, center, half, sliceOn)}
        {cloud.polylines.map((pl, i) => {
          if (!segInSlice(pl.pts, center, half, sliceOn)) return null;
          const col = byFov && DATA.fovColors[pl.fov] ? DATA.fovColors[pl.fov] : theme.stroke.secondary;
          const pts = proj === "XZ" ? pl.pts : pl.pts;
          return <polyline key={i} points={pts.map((p) => map(p).join(",")).join(" ")} fill="none" stroke={col} strokeWidth={1} />;
        })}
        {cloud.bps.map((b) => {
          if (!inSlice(b.z, center, half, sliceOn)) return null;
          const pt = proj === "XZ" ? [b.x, b.y, b.z] : [b.x, b.y, b.z];
          const [px, py] = map(pt);
          const on = sel === b.n;
          const col = on ? theme.accent.primary : (byFov && DATA.fovColors[b.fov] ? DATA.fovColors[b.fov] : fallback);
          return (
            <g key={b.n} onClick={() => onClick(b.n)} style={{ cursor: "pointer" }}>
              <circle cx={px} cy={py} r={on ? 7 : 4.5} fill={col} stroke={theme.bg.editor} strokeWidth={1} />
              <text x={px + 6} y={py - 6} fontSize={9} fill={theme.text.secondary}>{b.n}</text>
            </g>
          );
        })}
      </svg>
    </Stack>
  );

  const zControls = (
    lo: number, hi: number, val: number, set: (n: number) => void,
    half: number, setHalf: (n: number) => void, sliceOn: boolean, toggle: () => void, step: number,
  ) => (
    <Stack gap={6}>
      <Row gap={8} align="center" wrap>
        <Pill tone={sliceOn ? "info" : "neutral"} active={sliceOn} onClick={toggle}>Z slice</Pill>
        <Button variant="ghost" onClick={() => set(Math.max(lo, val - step))}>−{step}</Button>
        <Button variant="ghost" onClick={() => set(Math.min(hi, val + step))}>+{step}</Button>
        <Text size="small" tone="tertiary">z = {val.toFixed(0)} µm</Text>
      </Row>
      <Row gap={8} align="center">
        <Text size="small" tone="tertiary" style={{ width: 72 }}>depth</Text>
        <input type="range" min={lo} max={hi} step={Math.max(1, (hi - lo) / 200)} value={val}
          onChange={(e: any) => set(Number(e.target.value))} style={{ flex: 1, minWidth: 120 }} />
      </Row>
      <Row gap={8} align="center">
        <Text size="small" tone="tertiary" style={{ width: 72 }}>thickness ±{half.toFixed(0)} µm</Text>
        <input type="range" min={2} max={Math.max(10, (hi - lo) / 4)} step={1} value={half}
          onChange={(e: any) => setHalf(Number(e.target.value))} style={{ flex: 1, minWidth: 120 }} />
      </Row>
    </Stack>
  );

  const overlay = () => (
    <svg width={W} height={H * 2 + 4} style={{ background: theme.bg.elevated, borderRadius: 6, border: "1px solid " + theme.stroke.tertiary }}>
      {DATA.cell.polylines.map((pl, i) => (
        <polyline key={"c" + i} points={pl.pts.map((p) => cellMapXY(p).join(",")).join(" ")} fill="none" stroke={theme.stroke.tertiary} strokeWidth={1} />
      ))}
      {fit && DATA.mosaic.polylines.map((pl, i) => {
        const col = DATA.fovColors[pl.fov] || theme.accent.primary;
        return <polyline key={"m" + i} points={pl.pts.map((p) => cellMapXY(applySim(fit, p)).join(",")).join(" ")} fill="none" stroke={col} strokeWidth={1.2} />;
      })}
      {fit && pairs.map((pr, i) => {
        const mn = pr[0], cn = pr[1];
        if (!mosBy[mn] || !cellBy[cn]) return null;
        const m = cellMapXY(applySim(fit, [mosBy[mn].x, mosBy[mn].y]));
        const c = cellMapXY([cellBy[cn].x, cellBy[cn].y]);
        return <line key={i} x1={m[0]} y1={m[1]} x2={c[0]} y2={c[1]} stroke={theme.text.tertiary} strokeWidth={0.8} />;
      })}
    </svg>
  );

  const fovKeys = Object.keys(DATA.fovColors);

  return (
    <Stack gap={16} style={{ padding: 16 }}>
      <Stack gap={4}>
        <H2>Branch-point registration — {DATA.animal} / {DATA.session}</H2>
        <Text tone="secondary">Click a branch point on the cell, then its match on the mosaic, then Add pair. Use the depth slider and ± buttons to move through Z; XZ side views show depth. Toggle Z slice off to see everything.</Text>
      </Stack>

      {fovKeys.length > 0 && (
        <Row gap={12} align="center" wrap>
          <Text size="small" tone="tertiary">FOV:</Text>
          {fovKeys.map((f) => (
            <Row key={f} gap={4} align="center">
              <span style={{ width: 10, height: 10, background: DATA.fovColors[f], borderRadius: 2, display: "inline-block" }} />
              <Text size="small">{f}</Text>
            </Row>
          ))}
        </Row>
      )}

      <Row gap={20} align="center">
        <Pill tone={pairs.length >= 3 ? "success" : "neutral"}>{pairs.length} pairs</Pill>
        {fitRms != null ? <Stat label="Fit RMS (XY, um)" value={fitRms.toFixed(2)} /> : <Text tone="tertiary">Need ≥2 pairs to fit</Text>}
        <Stat label="Scale" value={fit ? fit.s.toFixed(3) : "—"} />
        <Stat label="Rotation (deg)" value={fit ? (Math.atan2(fit.sin, fit.cos) * 180 / Math.PI).toFixed(1) : "—"} />
      </Row>

      <Grid columns={3} gap={12}>
        <Stack gap={8}>
          <H3>Whole-cell (cell_n)</H3>
          {drawPanel(DATA.cell, cellMapXY, cellMapXZ, selCell, (n) => setSelCell(n), theme.text.link, cellZ, cellHalf, sliceCell, false, "XY (top view)")}
          {drawPanel(DATA.cell, cellMapXZ, cellMapXZ, selCell, (n) => setSelCell(n), theme.text.link, cellZ, cellHalf, sliceCell, false, "XZ (side view — dashed line = current Z)")}
          {zControls(cz0, cz1, cellZ, setCellZ, cellHalf, setCellHalf, sliceCell, () => setSliceCell(!sliceCell), 10)}
          <Text tone="tertiary">selected: {selCell == null ? "—" : selCell + (cellBy[selCell] ? " (z=" + cellBy[selCell].z.toFixed(0) + " µm)" : "")}</Text>
        </Stack>
        <Stack gap={8}>
          <H3>FOV mosaic (mosaic_n)</H3>
          {drawPanel(DATA.mosaic, mosMapXY, mosMapXZ, selMosaic, (n) => setSelMosaic(n), theme.accent.primary, mosZ, mosHalf, sliceMos, true, "XY (top view)")}
          {drawPanel(DATA.mosaic, mosMapXZ, mosMapXZ, selMosaic, (n) => setSelMosaic(n), theme.accent.primary, mosZ, mosHalf, sliceMos, true, "XZ (side view)")}
          {zControls(mz0, mz1, mosZ, setMosZ, mosHalf, setMosHalf, sliceMos, () => setSliceMos(!sliceMos), 2)}
          <Text tone="tertiary">selected: {selMosaic == null ? "—" : selMosaic + (mosBy[selMosaic] ? " (" + mosBy[selMosaic].fov + ", z=" + mosBy[selMosaic].z.toFixed(0) + " µm)" : "")}</Text>
        </Stack>
        <Stack gap={8}>
          <H3>Overlay (mosaic → cell)</H3>
          {overlay()}
          <Text tone="tertiary">colored = mosaic mapped onto grey cell (XY only)</Text>
        </Stack>
      </Grid>

      <Row gap={8}>
        <Button onClick={addPair} disabled={selCell == null || selMosaic == null}>Add pair{selMosaic != null && selCell != null ? " (" + selMosaic + " → " + selCell + ")" : ""}</Button>
        <Button variant="secondary" onClick={() => { setPairs([]); setSelCell(null); setSelMosaic(null); }}>Clear all</Button>
      </Row>

      {pairs.length > 0 && (
        <Card>
          <CardHeader>Pairs</CardHeader>
          <CardBody>
            <Stack gap={4}>
              {pairs.map((pr, i) => (
                <Row key={i} gap={8} align="center">
                  <Text>mosaic {pr[0]} → cell {pr[1]}</Text>
                  <Button variant="ghost" onClick={() => removePair(i)}>remove</Button>
                </Row>
              ))}
            </Stack>
          </CardBody>
        </Card>
      )}

      {pairs.length >= 3 ? (
        <Stack gap={8}>
          <H3>Paste into config/pairs_{DATA.session}.csv</H3>
          <Code style={{ whiteSpace: "pre" }}>{csv}</Code>
          <Callout tone="info">Then set "branchpoint_pairs": "config/pairs_{DATA.session}.csv" in GP04.json and re-run run_tree_analysis.py.</Callout>
        </Stack>
      ) : (
        <Callout tone="warning">Add at least 3 well-spread pairs (different FOVs) before exporting.</Callout>
      )}
    </Stack>
  );
}
"""


def main(argv: List[str]) -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass
    parser = argparse.ArgumentParser(description="Generate the manual branch-point pairing canvas.")
    parser.add_argument("run_dir", help="TreeAnalysis results run folder")
    parser.add_argument("--session", required=True, help="session name (e.g. pre-droplet)")
    parser.add_argument("--animal", default=None, help="animal id (defaults to parsed from folder)")
    parser.add_argument("--stride", type=int, default=4, help="skeleton decimation stride for display")
    args = parser.parse_args(argv[1:])

    run_dir = Path(args.run_dir)
    animal = args.animal or run_dir.name.split("_")[-1]
    data = build_data(run_dir, args.session, animal, args.stride)
    tsx = _TSX_TEMPLATE.replace("/*DATA_JSON*/", json.dumps(data))

    CANVAS_DIR.mkdir(parents=True, exist_ok=True)
    out = CANVAS_DIR / f"treeanalysis-{animal}-{args.session}.canvas.tsx"
    out.write_text(tsx, encoding="utf-8")
    print(f"cell polylines : {len(data['cell']['polylines'])}  ({len(data['cell']['bps'])} branch points)")
    print(f"mosaic polylines: {len(data['mosaic']['polylines'])}  ({len(data['mosaic']['bps'])} branch points)")
    print(f"fovs           : {list(data['fovColors'].keys())}")
    print(f"wrote canvas -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
